services:
  nextjs:
    build: ./nextjs-app
    platform: linux/arm64
    container_name: nextjs-app-test
    ports:
      - "3003:3000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  worker_vpn_add:
    # build: ./worker_vpn
    image: worker_add:latest
    container_name: add-vpn-client-worker
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      POSTGRES_URL: "${POSTGRES_URL}"
    depends_on:
      - rabbitmq
      - nextjs

  worker_vpn_config:
    # build: ./worker_config
    image: worker_config:latest
    container_name: create-vpn-server-config-worker
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      POSTGRES_URL: "${POSTGRES_URL}"
    depends_on:
      - rabbitmq
      - nextjs

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-neon
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  adminer_data:
  postgres_data:
